[project]
name = "meshcentral-meeting-calendar"
version = "0.1.0"
description = ""
authors = ["Sammy Ndabo <ndabosam084@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "ics>=0.7.2",
    "python-dateutil>=2.9.0.post0",
]
